publisher:
  name: Istituto Nazionale di Geofisica e Vulcanologia
  description: |
  L'Istituto Nazionale di Geofisica e Vulcanologia (INGV) è un Ente pubblico di ricerca non strumentale, dotato di personalità giuridica di diritto pubblico e di ordinamento autonomo, che realizza attività di ricerca nel campo delle discipline geofisiche nel campo dei Terremoti, dei Vulcani e dell'Ambiente e che si prefigge di assicurare una ricerca e un'innovazione responsabile mettendo i risultati della ricerca a disposizione di tutti, secondo le norme ed i principi riportati nel presente documento, e favorendo la partecipazione della società.
L'INGV è responsabile del servizio di sorveglianza sismica, vulcanica e dei maremoti nel territorio nazionale e nell'area mediterranea; coordina l'attività delle reti sismiche regionali e locali; partecipa alle reti di studio e di sorveglianza europee e globali; svolge attività di divulgazione e promuove iniziative di comunicazione, informazione e formazione nella scuola e nella società ai fini della riduzione del rischio associato alle fenomenologie relative alle proprie aree di ricerca; è componente del Servizio Nazionale di Protezione Civile, nonché Centro di Competenza del Dipartimento della Protezione Civile per conto del quale mantiene operative attività di sorveglianza h24 ed effettua progetti di ricerca con obiettivi dedicati nell'ambito di specifiche convenzioni.
  github_organization_url: github.com/ingv
  short_name: INGV
  website: https://www.ingv.it
  tags:
    - documenti
    - politica dei dati
    - pubblico
    - ricerca
    - scienze
    - terremoti
    - vulcani
    - ambiente
  logo: assets/images/INGV_LOGO.png
